### ISSUE TITLE
Build failure: Chrome download

### ISSUE THREAD

**Issue by rubenskuhl** [CENTRprojects/Signs-of-life#1]
`=> ERROR [ 9/13] RUN wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/ma  1.1s
------                                                                                                          
 > [ 9/13] RUN wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_115.0.5790.110-1_amd64.deb   && apt install -y /tmp/chrome.deb   && rm /tmp/chrome.deb:
0.741 https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_115.0.5790.110-1_amd64.deb:
0.741 2024-08-26 12:48:52 ERROR 404: Not Found.
------
Dockerfile:25
--------------------
  24 |     ARG CHROME_VERSION="115.0.5790.110-1"
  25 | >>> RUN wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb \
  26 | >>>   && apt install -y /tmp/chrome.deb \
  27 | >>>   && rm /tmp/chrome.deb
  28 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb   && apt install -y /tmp/chrome.deb   && rm /tmp/chrome.deb" did not complete successfully: exit code: 8
ERROR: Service 'crawler' failed to build : Build failed
`

**Comment by rubenskuhl** [comment]
It seems that the download URL Chrome is incorrect in the Docker compose file; manual instructions point to a different URL that works, but I don't know if they are the same version that is required. 

Any hints ?

**Comment by rubenskuhl** [comment]
Uncommenting the following from Dockerfile made it build:

But because of #2 it's unclear whether this will work or if it just made it to build. 

``` RUN cd /tmp && \
     wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
     dpkg -i --force-all google-chrome-stable_current_amd64.deb && \
     apt -f -y install```

**Comment by dm430as** [comment]
Hey, 

basically it should be on the latest version but I'm not sure if in the current crawler build it will break dependencies 

You could try putting the latest version and see if it works properly 

I will look into it once I have time and will update, since I'm currently running on a version with the modifications and new features on my machine 

Lavie

**Comment by dm430as** [comment]
Iv'e checked my version, the chrome / chrome-driver installation was embedded into the entrypoint.sh script to run at first run of the docker to get the latest, will push the changes with the next commit once we finish testing
@rubenskuhl

**Comment by rubenskuhl** [comment]
> Iv'e checked my version, the chrome / chrome-driver installation was embedded into the entrypoint.sh script to run at first run of the docker to get the latest, will push the changes with the next commit once we finish testing @rubenskuhl

Will the next commit have a documentation update to handle #2 ?

**Comment by pawel-kow** [comment]
I faced the same issue and replaced the chrome version to the actual 128.0.6613.113-1 in Dockerfile.
This download is only available for amd64 platform, so for Mac M* an addition was needed to docker_compose to enforce that when building container otherwise it fails badly when trying to install missing dependencies.

**Comment by dm430as** [comment]
merged,thanks!
