### ISSUE TITLE
Run failure on Docker - hosting_companies_with_tld.csv

### ISSUE THREAD

**Issue by rubenskuhl** [CENTRprojects/Signs-of-life#2]
It was not quite clear how to add hosting_companies_with_tld.csv to the Docker image so it can be used by the crawler. 
If it's put into the .docker/data directory, it's parsed as a domain list, and removed before the next run of the crawler. 

Traceback (most recent call last):
crawler_1     |   File "app_domains/main_domains.py", line 19, in <module>
crawler_1     |     from classification_parked import predict_parking                       # DO_CONTENT_CLASSIFICATION
crawler_1     |   File "/signs-of-life/app_domains/classification_parked.py", line 40, in <module>
crawler_1     |     "hosting_companies_with_tld.csv"), encoding="latin-1").values.tolist()
crawler_1     |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
crawler_1     |     return _read(filepath_or_buffer, kwds)
crawler_1     |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
crawler_1     |     parser = TextFileReader(fp_or_buf, **kwds)
crawler_1     |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
crawler_1     |     self._make_engine(self.engine)
crawler_1     |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
crawler_1     |     self._engine = CParserWrapper(self.f, **self.options)
crawler_1     |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1891, in __init__
crawler_1     |     self._reader = parsers.TextReader(src, **kwds)
crawler_1     |   File "pandas/_libs/parsers.pyx", line 532, in pandas._libs.parsers.TextReader.__cinit__
crawler_1     | pandas.errors.EmptyDataError: No columns to parse from file

**Comment by pawel-kow** [comment]
I could work around this one by running in `input` folder:
```
touch hosting_companies_with_tld.csv
python3 insert_registrars.py "registrar url.txt"
```

Then I faced #3 which makes me think that there are more needed csv files missing.

**Comment by rubenskuhl** [comment]
> I could work around this one by running in `input` folder:
> 
> ```
> touch hosting_companies_with_tld.csv
> python3 insert_registrars.py "registrar url.txt"
> ```
> 
> Then I faced #3 which makes me think that there are more needed csv files missing.

But was it effective to the Docker version as well ?

**Comment by pawel-kow** [comment]
@rubenskuhl 
> But was it effective to the Docker version as well ?

Yes, this is in the mounted folder in the docker compose file
The container is not self-contained as such.

**Comment by pawel-kow** [comment]
@rubenskuhl please take a look if #5  will work for you to fix the issues with docker build and missing files

**Comment by dm430as** [comment]
merged, thanks!
